// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/study/signalcommon/MessageProto.proto

package com.study.signalcommon.proto;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string msgid = 1;</code>
     */
    java.lang.String getMsgid();
    /**
     * <code>string msgid = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgidBytes();

    /**
     * <code>string msgtype = 2;</code>
     */
    java.lang.String getMsgtype();
    /**
     * <code>string msgtype = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgtypeBytes();

    /**
     * <code>map&lt;string, string&gt; extend = 3;</code>
     */
    int getExtendCount();
    /**
     * <code>map&lt;string, string&gt; extend = 3;</code>
     */
    boolean containsExtend(
        java.lang.String key);
    /**
     * Use {@link #getExtendMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getExtend();
    /**
     * <code>map&lt;string, string&gt; extend = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getExtendMap();
    /**
     * <code>map&lt;string, string&gt; extend = 3;</code>
     */

    java.lang.String getExtendOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; extend = 3;</code>
     */

    java.lang.String getExtendOrThrow(
        java.lang.String key);

    /**
     * <code>.User fuser = 4;</code>
     */
    boolean hasFuser();
    /**
     * <code>.User fuser = 4;</code>
     */
    com.study.signalcommon.proto.MessageProto.User getFuser();
    /**
     * <code>.User fuser = 4;</code>
     */
    com.study.signalcommon.proto.MessageProto.UserOrBuilder getFuserOrBuilder();

    /**
     * <code>.User tser = 5;</code>
     */
    boolean hasTser();
    /**
     * <code>.User tser = 5;</code>
     */
    com.study.signalcommon.proto.MessageProto.User getTser();
    /**
     * <code>.User tser = 5;</code>
     */
    com.study.signalcommon.proto.MessageProto.UserOrBuilder getTserOrBuilder();
  }
  /**
   * Protobuf type {@code Msg}
   */
  public  static final class Msg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Msg)
      MsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Msg() {
      msgid_ = "";
      msgtype_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              msgid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msgtype_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                extend_ = com.google.protobuf.MapField.newMapField(
                    ExtendDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              extend__ = input.readMessage(
                  ExtendDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              extend_.getMutableMap().put(
                  extend__.getKey(), extend__.getValue());
              break;
            }
            case 34: {
              com.study.signalcommon.proto.MessageProto.User.Builder subBuilder = null;
              if (fuser_ != null) {
                subBuilder = fuser_.toBuilder();
              }
              fuser_ = input.readMessage(com.study.signalcommon.proto.MessageProto.User.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fuser_);
                fuser_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.study.signalcommon.proto.MessageProto.User.Builder subBuilder = null;
              if (tser_ != null) {
                subBuilder = tser_.toBuilder();
              }
              tser_ = input.readMessage(com.study.signalcommon.proto.MessageProto.User.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(tser_);
                tser_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.study.signalcommon.proto.MessageProto.internal_static_Msg_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetExtend();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.study.signalcommon.proto.MessageProto.internal_static_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.study.signalcommon.proto.MessageProto.Msg.class, com.study.signalcommon.proto.MessageProto.Msg.Builder.class);
    }

    private int bitField0_;
    public static final int MSGID_FIELD_NUMBER = 1;
    private volatile java.lang.Object msgid_;
    /**
     * <code>string msgid = 1;</code>
     */
    public java.lang.String getMsgid() {
      java.lang.Object ref = msgid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgid_ = s;
        return s;
      }
    }
    /**
     * <code>string msgid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgidBytes() {
      java.lang.Object ref = msgid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGTYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object msgtype_;
    /**
     * <code>string msgtype = 2;</code>
     */
    public java.lang.String getMsgtype() {
      java.lang.Object ref = msgtype_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgtype_ = s;
        return s;
      }
    }
    /**
     * <code>string msgtype = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgtypeBytes() {
      java.lang.Object ref = msgtype_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgtype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTEND_FIELD_NUMBER = 3;
    private static final class ExtendDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.study.signalcommon.proto.MessageProto.internal_static_Msg_ExtendEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> extend_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetExtend() {
      if (extend_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ExtendDefaultEntryHolder.defaultEntry);
      }
      return extend_;
    }

    public int getExtendCount() {
      return internalGetExtend().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; extend = 3;</code>
     */

    public boolean containsExtend(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetExtend().getMap().containsKey(key);
    }
    /**
     * Use {@link #getExtendMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getExtend() {
      return getExtendMap();
    }
    /**
     * <code>map&lt;string, string&gt; extend = 3;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getExtendMap() {
      return internalGetExtend().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; extend = 3;</code>
     */

    public java.lang.String getExtendOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExtend().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; extend = 3;</code>
     */

    public java.lang.String getExtendOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExtend().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int FUSER_FIELD_NUMBER = 4;
    private com.study.signalcommon.proto.MessageProto.User fuser_;
    /**
     * <code>.User fuser = 4;</code>
     */
    public boolean hasFuser() {
      return fuser_ != null;
    }
    /**
     * <code>.User fuser = 4;</code>
     */
    public com.study.signalcommon.proto.MessageProto.User getFuser() {
      return fuser_ == null ? com.study.signalcommon.proto.MessageProto.User.getDefaultInstance() : fuser_;
    }
    /**
     * <code>.User fuser = 4;</code>
     */
    public com.study.signalcommon.proto.MessageProto.UserOrBuilder getFuserOrBuilder() {
      return getFuser();
    }

    public static final int TSER_FIELD_NUMBER = 5;
    private com.study.signalcommon.proto.MessageProto.User tser_;
    /**
     * <code>.User tser = 5;</code>
     */
    public boolean hasTser() {
      return tser_ != null;
    }
    /**
     * <code>.User tser = 5;</code>
     */
    public com.study.signalcommon.proto.MessageProto.User getTser() {
      return tser_ == null ? com.study.signalcommon.proto.MessageProto.User.getDefaultInstance() : tser_;
    }
    /**
     * <code>.User tser = 5;</code>
     */
    public com.study.signalcommon.proto.MessageProto.UserOrBuilder getTserOrBuilder() {
      return getTser();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMsgidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgid_);
      }
      if (!getMsgtypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msgtype_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetExtend(),
          ExtendDefaultEntryHolder.defaultEntry,
          3);
      if (fuser_ != null) {
        output.writeMessage(4, getFuser());
      }
      if (tser_ != null) {
        output.writeMessage(5, getTser());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMsgidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgid_);
      }
      if (!getMsgtypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msgtype_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetExtend().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        extend__ = ExtendDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, extend__);
      }
      if (fuser_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getFuser());
      }
      if (tser_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getTser());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.study.signalcommon.proto.MessageProto.Msg)) {
        return super.equals(obj);
      }
      com.study.signalcommon.proto.MessageProto.Msg other = (com.study.signalcommon.proto.MessageProto.Msg) obj;

      if (!getMsgid()
          .equals(other.getMsgid())) return false;
      if (!getMsgtype()
          .equals(other.getMsgtype())) return false;
      if (!internalGetExtend().equals(
          other.internalGetExtend())) return false;
      if (hasFuser() != other.hasFuser()) return false;
      if (hasFuser()) {
        if (!getFuser()
            .equals(other.getFuser())) return false;
      }
      if (hasTser() != other.hasTser()) return false;
      if (hasTser()) {
        if (!getTser()
            .equals(other.getTser())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgid().hashCode();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgtype().hashCode();
      if (!internalGetExtend().getMap().isEmpty()) {
        hash = (37 * hash) + EXTEND_FIELD_NUMBER;
        hash = (53 * hash) + internalGetExtend().hashCode();
      }
      if (hasFuser()) {
        hash = (37 * hash) + FUSER_FIELD_NUMBER;
        hash = (53 * hash) + getFuser().hashCode();
      }
      if (hasTser()) {
        hash = (37 * hash) + TSER_FIELD_NUMBER;
        hash = (53 * hash) + getTser().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.study.signalcommon.proto.MessageProto.Msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.signalcommon.proto.MessageProto.Msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.signalcommon.proto.MessageProto.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.signalcommon.proto.MessageProto.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.signalcommon.proto.MessageProto.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.signalcommon.proto.MessageProto.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.signalcommon.proto.MessageProto.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.study.signalcommon.proto.MessageProto.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.study.signalcommon.proto.MessageProto.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.study.signalcommon.proto.MessageProto.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.study.signalcommon.proto.MessageProto.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.study.signalcommon.proto.MessageProto.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.study.signalcommon.proto.MessageProto.Msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Msg)
        com.study.signalcommon.proto.MessageProto.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.study.signalcommon.proto.MessageProto.internal_static_Msg_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetExtend();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableExtend();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.study.signalcommon.proto.MessageProto.internal_static_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.study.signalcommon.proto.MessageProto.Msg.class, com.study.signalcommon.proto.MessageProto.Msg.Builder.class);
      }

      // Construct using com.study.signalcommon.proto.MessageProto.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgid_ = "";

        msgtype_ = "";

        internalGetMutableExtend().clear();
        if (fuserBuilder_ == null) {
          fuser_ = null;
        } else {
          fuser_ = null;
          fuserBuilder_ = null;
        }
        if (tserBuilder_ == null) {
          tser_ = null;
        } else {
          tser_ = null;
          tserBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.study.signalcommon.proto.MessageProto.internal_static_Msg_descriptor;
      }

      @java.lang.Override
      public com.study.signalcommon.proto.MessageProto.Msg getDefaultInstanceForType() {
        return com.study.signalcommon.proto.MessageProto.Msg.getDefaultInstance();
      }

      @java.lang.Override
      public com.study.signalcommon.proto.MessageProto.Msg build() {
        com.study.signalcommon.proto.MessageProto.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.study.signalcommon.proto.MessageProto.Msg buildPartial() {
        com.study.signalcommon.proto.MessageProto.Msg result = new com.study.signalcommon.proto.MessageProto.Msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.msgid_ = msgid_;
        result.msgtype_ = msgtype_;
        result.extend_ = internalGetExtend();
        result.extend_.makeImmutable();
        if (fuserBuilder_ == null) {
          result.fuser_ = fuser_;
        } else {
          result.fuser_ = fuserBuilder_.build();
        }
        if (tserBuilder_ == null) {
          result.tser_ = tser_;
        } else {
          result.tser_ = tserBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.study.signalcommon.proto.MessageProto.Msg) {
          return mergeFrom((com.study.signalcommon.proto.MessageProto.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.study.signalcommon.proto.MessageProto.Msg other) {
        if (other == com.study.signalcommon.proto.MessageProto.Msg.getDefaultInstance()) return this;
        if (!other.getMsgid().isEmpty()) {
          msgid_ = other.msgid_;
          onChanged();
        }
        if (!other.getMsgtype().isEmpty()) {
          msgtype_ = other.msgtype_;
          onChanged();
        }
        internalGetMutableExtend().mergeFrom(
            other.internalGetExtend());
        if (other.hasFuser()) {
          mergeFuser(other.getFuser());
        }
        if (other.hasTser()) {
          mergeTser(other.getTser());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.study.signalcommon.proto.MessageProto.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.study.signalcommon.proto.MessageProto.Msg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object msgid_ = "";
      /**
       * <code>string msgid = 1;</code>
       */
      public java.lang.String getMsgid() {
        java.lang.Object ref = msgid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msgid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgidBytes() {
        java.lang.Object ref = msgid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msgid = 1;</code>
       */
      public Builder setMsgid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msgid = 1;</code>
       */
      public Builder clearMsgid() {
        
        msgid_ = getDefaultInstance().getMsgid();
        onChanged();
        return this;
      }
      /**
       * <code>string msgid = 1;</code>
       */
      public Builder setMsgidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object msgtype_ = "";
      /**
       * <code>string msgtype = 2;</code>
       */
      public java.lang.String getMsgtype() {
        java.lang.Object ref = msgtype_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgtype_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msgtype = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgtypeBytes() {
        java.lang.Object ref = msgtype_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgtype_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msgtype = 2;</code>
       */
      public Builder setMsgtype(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msgtype = 2;</code>
       */
      public Builder clearMsgtype() {
        
        msgtype_ = getDefaultInstance().getMsgtype();
        onChanged();
        return this;
      }
      /**
       * <code>string msgtype = 2;</code>
       */
      public Builder setMsgtypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgtype_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> extend_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetExtend() {
        if (extend_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ExtendDefaultEntryHolder.defaultEntry);
        }
        return extend_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableExtend() {
        onChanged();;
        if (extend_ == null) {
          extend_ = com.google.protobuf.MapField.newMapField(
              ExtendDefaultEntryHolder.defaultEntry);
        }
        if (!extend_.isMutable()) {
          extend_ = extend_.copy();
        }
        return extend_;
      }

      public int getExtendCount() {
        return internalGetExtend().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; extend = 3;</code>
       */

      public boolean containsExtend(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetExtend().getMap().containsKey(key);
      }
      /**
       * Use {@link #getExtendMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getExtend() {
        return getExtendMap();
      }
      /**
       * <code>map&lt;string, string&gt; extend = 3;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getExtendMap() {
        return internalGetExtend().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; extend = 3;</code>
       */

      public java.lang.String getExtendOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetExtend().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; extend = 3;</code>
       */

      public java.lang.String getExtendOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetExtend().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearExtend() {
        internalGetMutableExtend().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; extend = 3;</code>
       */

      public Builder removeExtend(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableExtend().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableExtend() {
        return internalGetMutableExtend().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; extend = 3;</code>
       */
      public Builder putExtend(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableExtend().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; extend = 3;</code>
       */

      public Builder putAllExtend(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableExtend().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.study.signalcommon.proto.MessageProto.User fuser_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.study.signalcommon.proto.MessageProto.User, com.study.signalcommon.proto.MessageProto.User.Builder, com.study.signalcommon.proto.MessageProto.UserOrBuilder> fuserBuilder_;
      /**
       * <code>.User fuser = 4;</code>
       */
      public boolean hasFuser() {
        return fuserBuilder_ != null || fuser_ != null;
      }
      /**
       * <code>.User fuser = 4;</code>
       */
      public com.study.signalcommon.proto.MessageProto.User getFuser() {
        if (fuserBuilder_ == null) {
          return fuser_ == null ? com.study.signalcommon.proto.MessageProto.User.getDefaultInstance() : fuser_;
        } else {
          return fuserBuilder_.getMessage();
        }
      }
      /**
       * <code>.User fuser = 4;</code>
       */
      public Builder setFuser(com.study.signalcommon.proto.MessageProto.User value) {
        if (fuserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fuser_ = value;
          onChanged();
        } else {
          fuserBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.User fuser = 4;</code>
       */
      public Builder setFuser(
          com.study.signalcommon.proto.MessageProto.User.Builder builderForValue) {
        if (fuserBuilder_ == null) {
          fuser_ = builderForValue.build();
          onChanged();
        } else {
          fuserBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.User fuser = 4;</code>
       */
      public Builder mergeFuser(com.study.signalcommon.proto.MessageProto.User value) {
        if (fuserBuilder_ == null) {
          if (fuser_ != null) {
            fuser_ =
              com.study.signalcommon.proto.MessageProto.User.newBuilder(fuser_).mergeFrom(value).buildPartial();
          } else {
            fuser_ = value;
          }
          onChanged();
        } else {
          fuserBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.User fuser = 4;</code>
       */
      public Builder clearFuser() {
        if (fuserBuilder_ == null) {
          fuser_ = null;
          onChanged();
        } else {
          fuser_ = null;
          fuserBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.User fuser = 4;</code>
       */
      public com.study.signalcommon.proto.MessageProto.User.Builder getFuserBuilder() {
        
        onChanged();
        return getFuserFieldBuilder().getBuilder();
      }
      /**
       * <code>.User fuser = 4;</code>
       */
      public com.study.signalcommon.proto.MessageProto.UserOrBuilder getFuserOrBuilder() {
        if (fuserBuilder_ != null) {
          return fuserBuilder_.getMessageOrBuilder();
        } else {
          return fuser_ == null ?
              com.study.signalcommon.proto.MessageProto.User.getDefaultInstance() : fuser_;
        }
      }
      /**
       * <code>.User fuser = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.study.signalcommon.proto.MessageProto.User, com.study.signalcommon.proto.MessageProto.User.Builder, com.study.signalcommon.proto.MessageProto.UserOrBuilder> 
          getFuserFieldBuilder() {
        if (fuserBuilder_ == null) {
          fuserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.study.signalcommon.proto.MessageProto.User, com.study.signalcommon.proto.MessageProto.User.Builder, com.study.signalcommon.proto.MessageProto.UserOrBuilder>(
                  getFuser(),
                  getParentForChildren(),
                  isClean());
          fuser_ = null;
        }
        return fuserBuilder_;
      }

      private com.study.signalcommon.proto.MessageProto.User tser_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.study.signalcommon.proto.MessageProto.User, com.study.signalcommon.proto.MessageProto.User.Builder, com.study.signalcommon.proto.MessageProto.UserOrBuilder> tserBuilder_;
      /**
       * <code>.User tser = 5;</code>
       */
      public boolean hasTser() {
        return tserBuilder_ != null || tser_ != null;
      }
      /**
       * <code>.User tser = 5;</code>
       */
      public com.study.signalcommon.proto.MessageProto.User getTser() {
        if (tserBuilder_ == null) {
          return tser_ == null ? com.study.signalcommon.proto.MessageProto.User.getDefaultInstance() : tser_;
        } else {
          return tserBuilder_.getMessage();
        }
      }
      /**
       * <code>.User tser = 5;</code>
       */
      public Builder setTser(com.study.signalcommon.proto.MessageProto.User value) {
        if (tserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          tser_ = value;
          onChanged();
        } else {
          tserBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.User tser = 5;</code>
       */
      public Builder setTser(
          com.study.signalcommon.proto.MessageProto.User.Builder builderForValue) {
        if (tserBuilder_ == null) {
          tser_ = builderForValue.build();
          onChanged();
        } else {
          tserBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.User tser = 5;</code>
       */
      public Builder mergeTser(com.study.signalcommon.proto.MessageProto.User value) {
        if (tserBuilder_ == null) {
          if (tser_ != null) {
            tser_ =
              com.study.signalcommon.proto.MessageProto.User.newBuilder(tser_).mergeFrom(value).buildPartial();
          } else {
            tser_ = value;
          }
          onChanged();
        } else {
          tserBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.User tser = 5;</code>
       */
      public Builder clearTser() {
        if (tserBuilder_ == null) {
          tser_ = null;
          onChanged();
        } else {
          tser_ = null;
          tserBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.User tser = 5;</code>
       */
      public com.study.signalcommon.proto.MessageProto.User.Builder getTserBuilder() {
        
        onChanged();
        return getTserFieldBuilder().getBuilder();
      }
      /**
       * <code>.User tser = 5;</code>
       */
      public com.study.signalcommon.proto.MessageProto.UserOrBuilder getTserOrBuilder() {
        if (tserBuilder_ != null) {
          return tserBuilder_.getMessageOrBuilder();
        } else {
          return tser_ == null ?
              com.study.signalcommon.proto.MessageProto.User.getDefaultInstance() : tser_;
        }
      }
      /**
       * <code>.User tser = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.study.signalcommon.proto.MessageProto.User, com.study.signalcommon.proto.MessageProto.User.Builder, com.study.signalcommon.proto.MessageProto.UserOrBuilder> 
          getTserFieldBuilder() {
        if (tserBuilder_ == null) {
          tserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.study.signalcommon.proto.MessageProto.User, com.study.signalcommon.proto.MessageProto.User.Builder, com.study.signalcommon.proto.MessageProto.UserOrBuilder>(
                  getTser(),
                  getParentForChildren(),
                  isClean());
          tser_ = null;
        }
        return tserBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Msg)
    }

    // @@protoc_insertion_point(class_scope:Msg)
    private static final com.study.signalcommon.proto.MessageProto.Msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.study.signalcommon.proto.MessageProto.Msg();
    }

    public static com.study.signalcommon.proto.MessageProto.Msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Msg>
        PARSER = new com.google.protobuf.AbstractParser<Msg>() {
      @java.lang.Override
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Msg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.study.signalcommon.proto.MessageProto.Msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string rid = 1;</code>
     */
    java.lang.String getRid();
    /**
     * <code>string rid = 1;</code>
     */
    com.google.protobuf.ByteString
        getRidBytes();

    /**
     * <code>string uid = 2;</code>
     */
    java.lang.String getUid();
    /**
     * <code>string uid = 2;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <code>string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string img = 4;</code>
     */
    java.lang.String getImg();
    /**
     * <code>string img = 4;</code>
     */
    com.google.protobuf.ByteString
        getImgBytes();
  }
  /**
   * Protobuf type {@code User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      rid_ = "";
      uid_ = "";
      name_ = "";
      img_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              rid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              img_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.study.signalcommon.proto.MessageProto.internal_static_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.study.signalcommon.proto.MessageProto.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.study.signalcommon.proto.MessageProto.User.class, com.study.signalcommon.proto.MessageProto.User.Builder.class);
    }

    public static final int RID_FIELD_NUMBER = 1;
    private volatile java.lang.Object rid_;
    /**
     * <code>string rid = 1;</code>
     */
    public java.lang.String getRid() {
      java.lang.Object ref = rid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rid_ = s;
        return s;
      }
    }
    /**
     * <code>string rid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRidBytes() {
      java.lang.Object ref = rid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UID_FIELD_NUMBER = 2;
    private volatile java.lang.Object uid_;
    /**
     * <code>string uid = 2;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <code>string uid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMG_FIELD_NUMBER = 4;
    private volatile java.lang.Object img_;
    /**
     * <code>string img = 4;</code>
     */
    public java.lang.String getImg() {
      java.lang.Object ref = img_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        img_ = s;
        return s;
      }
    }
    /**
     * <code>string img = 4;</code>
     */
    public com.google.protobuf.ByteString
        getImgBytes() {
      java.lang.Object ref = img_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        img_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rid_);
      }
      if (!getUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uid_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (!getImgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, img_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, rid_);
      }
      if (!getUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, uid_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (!getImgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, img_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.study.signalcommon.proto.MessageProto.User)) {
        return super.equals(obj);
      }
      com.study.signalcommon.proto.MessageProto.User other = (com.study.signalcommon.proto.MessageProto.User) obj;

      if (!getRid()
          .equals(other.getRid())) return false;
      if (!getUid()
          .equals(other.getUid())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getImg()
          .equals(other.getImg())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RID_FIELD_NUMBER;
      hash = (53 * hash) + getRid().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + IMG_FIELD_NUMBER;
      hash = (53 * hash) + getImg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.study.signalcommon.proto.MessageProto.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.signalcommon.proto.MessageProto.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.signalcommon.proto.MessageProto.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.signalcommon.proto.MessageProto.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.signalcommon.proto.MessageProto.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.signalcommon.proto.MessageProto.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.signalcommon.proto.MessageProto.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.study.signalcommon.proto.MessageProto.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.study.signalcommon.proto.MessageProto.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.study.signalcommon.proto.MessageProto.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.study.signalcommon.proto.MessageProto.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.study.signalcommon.proto.MessageProto.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.study.signalcommon.proto.MessageProto.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        com.study.signalcommon.proto.MessageProto.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.study.signalcommon.proto.MessageProto.internal_static_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.study.signalcommon.proto.MessageProto.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.study.signalcommon.proto.MessageProto.User.class, com.study.signalcommon.proto.MessageProto.User.Builder.class);
      }

      // Construct using com.study.signalcommon.proto.MessageProto.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        rid_ = "";

        uid_ = "";

        name_ = "";

        img_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.study.signalcommon.proto.MessageProto.internal_static_User_descriptor;
      }

      @java.lang.Override
      public com.study.signalcommon.proto.MessageProto.User getDefaultInstanceForType() {
        return com.study.signalcommon.proto.MessageProto.User.getDefaultInstance();
      }

      @java.lang.Override
      public com.study.signalcommon.proto.MessageProto.User build() {
        com.study.signalcommon.proto.MessageProto.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.study.signalcommon.proto.MessageProto.User buildPartial() {
        com.study.signalcommon.proto.MessageProto.User result = new com.study.signalcommon.proto.MessageProto.User(this);
        result.rid_ = rid_;
        result.uid_ = uid_;
        result.name_ = name_;
        result.img_ = img_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.study.signalcommon.proto.MessageProto.User) {
          return mergeFrom((com.study.signalcommon.proto.MessageProto.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.study.signalcommon.proto.MessageProto.User other) {
        if (other == com.study.signalcommon.proto.MessageProto.User.getDefaultInstance()) return this;
        if (!other.getRid().isEmpty()) {
          rid_ = other.rid_;
          onChanged();
        }
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getImg().isEmpty()) {
          img_ = other.img_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.study.signalcommon.proto.MessageProto.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.study.signalcommon.proto.MessageProto.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object rid_ = "";
      /**
       * <code>string rid = 1;</code>
       */
      public java.lang.String getRid() {
        java.lang.Object ref = rid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRidBytes() {
        java.lang.Object ref = rid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rid = 1;</code>
       */
      public Builder setRid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string rid = 1;</code>
       */
      public Builder clearRid() {
        
        rid_ = getDefaultInstance().getRid();
        onChanged();
        return this;
      }
      /**
       * <code>string rid = 1;</code>
       */
      public Builder setRidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object uid_ = "";
      /**
       * <code>string uid = 2;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uid = 2;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 2;</code>
       */
      public Builder clearUid() {
        
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 2;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object img_ = "";
      /**
       * <code>string img = 4;</code>
       */
      public java.lang.String getImg() {
        java.lang.Object ref = img_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          img_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string img = 4;</code>
       */
      public com.google.protobuf.ByteString
          getImgBytes() {
        java.lang.Object ref = img_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          img_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string img = 4;</code>
       */
      public Builder setImg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        img_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string img = 4;</code>
       */
      public Builder clearImg() {
        
        img_ = getDefaultInstance().getImg();
        onChanged();
        return this;
      }
      /**
       * <code>string img = 4;</code>
       */
      public Builder setImgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        img_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final com.study.signalcommon.proto.MessageProto.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.study.signalcommon.proto.MessageProto.User();
    }

    public static com.study.signalcommon.proto.MessageProto.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.study.signalcommon.proto.MessageProto.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Msg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_ExtendEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Msg_ExtendEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)com/study/signalcommon/MessageProto.pr" +
      "oto\"\241\001\n\003Msg\022\r\n\005msgid\030\001 \001(\t\022\017\n\007msgtype\030\002 " +
      "\001(\t\022 \n\006extend\030\003 \003(\0132\020.Msg.ExtendEntry\022\024\n" +
      "\005fuser\030\004 \001(\0132\005.User\022\023\n\004tser\030\005 \001(\0132\005.User" +
      "\032-\n\013ExtendEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\t:\0028\001\";\n\004User\022\013\n\003rid\030\001 \001(\t\022\013\n\003uid\030\002 \001(" +
      "\t\022\014\n\004name\030\003 \001(\t\022\013\n\003img\030\004 \001(\tB,\n\034com.stud" +
      "y.signalcommon.protoB\014MessageProtob\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Msg_descriptor,
        new java.lang.String[] { "Msgid", "Msgtype", "Extend", "Fuser", "Tser", });
    internal_static_Msg_ExtendEntry_descriptor =
      internal_static_Msg_descriptor.getNestedTypes().get(0);
    internal_static_Msg_ExtendEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Msg_ExtendEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Rid", "Uid", "Name", "Img", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
